version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo_network
  db:
    image: postgres:15
    environment:  # "environnement" corrigé en "environment"
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata  # PGDATA corrigé pour correspondre au chemin du volume
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata  # "pgdata" ajouté pour correspondre à PGDATA
    networks:
      - odoo_network

volumes:
  # odoo-web-data:  # Volume retiré car non utilisé dans le fichier
  odoo-db-data:

networks:
  odoo_network:

